services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_for_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123654
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
